# Generated by Django 2.0.6 on 2020-05-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('n_genomes', models.IntegerField(blank=True, default=0, null=True)),
                ('genomes_file', models.FileField(blank=True, null=True, upload_to='')),
                ('alignment_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=2000)),
                ('representation', models.ImageField(blank=True, null=True, upload_to='')),
                ('newick_structure', models.FileField(blank=True, null=True, upload_to='')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='maps.Alignment')),
            ],
        ),
    ]
