# Generated by Django 2.0.6 on 2020-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200502_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='n_genomes',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='data',
        ),
        migrations.AddField(
            model_name='representation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='representation',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='info_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
