# Generated by Django 2.0.6 on 2020-05-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20200502_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
