# Generated by Django 2.0.6 on 2020-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20200503_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representation',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='representation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
