# Generated by Django 2.0.6 on 2020-05-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20200503_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='image',
        ),
        migrations.AddField(
            model_name='representation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
