# Generated by Django 2.0.6 on 2020-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20200503_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='tag',
            field=models.CharField(default='default_tag', max_length=20),
        ),
    ]
