# Generated by Django 2.0.6 on 2020-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_tree_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='alignment_file',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='info_file',
        ),
        migrations.AddField(
            model_name='alignment',
            name='processed_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='genomes_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='newick_structure',
            field=models.CharField(blank=True, max_length=200000, null=True),
        ),
    ]
