# Generated by Django 2.0.6 on 2020-05-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20200504_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='tag',
            field=models.CharField(default='default_tag', max_length=20),
        ),
    ]
