# Generated by Django 2.0.6 on 2020-05-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alignment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='newick_structure',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
    ]
