# Generated by Django 2.0.6 on 2020-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20200504_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representation',
            old_name='image_url',
            new_name='image',
        ),
    ]
