# Generated by Django 2.0.6 on 2020-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20200504_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='tag',
            field=models.CharField(default='default_tag', max_length=20),
        ),
    ]
