# Generated by Django 2.0.6 on 2020-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_representation_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='image',
        ),
        migrations.AddField(
            model_name='representation',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
