# Generated by Django 2.0.6 on 2020-05-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20200504_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='layout',
            field=models.CharField(default='pi', max_length=2),
        ),
        migrations.AddField(
            model_name='tree',
            name='layout',
            field=models.CharField(default='pi', max_length=2),
        ),
    ]
